# Generated by Django 5.1.2 on 2024-10-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp_provider', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('Broadband', 'Broadband'), ('Leased', 'Leased'), ('Semi Leased', 'Semi Leased')], max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('ppoe_username', models.CharField(max_length=50)),
                ('ppoe_password', models.CharField(max_length=50)),
                ('static_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('subnet_mask', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway', models.CharField(blank=True, max_length=50, null=True)),
                ('dns1', models.CharField(blank=True, max_length=50, null=True)),
                ('dns2', models.CharField(blank=True, max_length=50, null=True)),
                ('local_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('vpn_type', models.CharField(blank=True, choices=[('IPSEC', 'IPSEC'), ('SSL', 'SSL')], max_length=20, null=True)),
                ('ssl_username', models.CharField(blank=True, max_length=50, null=True)),
                ('ssl_password', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_type', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('Off Yearly', 'Off Yearly'), ('Yearly', 'Yearly')], max_length=20)),
                ('monthly_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engineer', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='branches.branch')),
            ],
        ),
    ]
